### ISSUE TITLE
liquibase relative to changelog in folder reference broken

### ISSUE THREAD

**Issue by merijnv** [jpa-buddy/documentation#22]
After updating to 2021.6.2-213 click through from the master changelog file to included files is broken:

Screen-shot:
![image](https://user-images.githubusercontent.com/8720747/151013062-f0b7f0d9-7adc-4b3b-9694-a93dc5ff0990.png)

These used to be green and would bring you to the actual file (with control-click).

**Comment by merijnv** [comment]
Just ouside of the screenshot:

relativeToChangelog="true"

and the relative path is correct.

**Comment by honest-niceman** [comment]
Hi Merijnv,

Thanks for using JPA Buddy and reporting issues.

But, this is a repository for documentation only, so I'll close it here and moved your ticket over into our internal issue tracker. [Here](https://issues.jpa-buddy.com/issue/JPAB-1603) is the link that you may use to follow its status.

We didn't expect to see the request in this repository :) That's why it's taken so long to answer. If in the future you see a bug or want to offer any feature that is missing, we will give you a response a lot quicker in the [discord](https://discord.com/invite/DxRDQPk9rh) or [email](https://www.jpa-buddy.com/contacts/).
